### ISSUE TITLE
Cassandra password authentication is still broken

### ISSUE THREAD

**Issue by veselov** [exoscale/pithos#109]
Even though #87 was closed, the problem is not fixed.
Attempt to authenticate Cassandra connection throws NPE that is translated by the driver to just saying it can't connect:

`ERROR [2016-08-31 13:43:57,722] main - io.pithos.config invalid or incomplete configuration
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.ConnectionException: [/127.0.0.1] Unexpected error during transport initialization (java.lang.NullPointerException)))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1430) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.Cluster.init(Cluster.java:163) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:309) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:251) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at qbits.alia$connect.invokeStatic(alia.clj:185) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at qbits.alia$connect.invoke(alia.clj:178) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.store$cassandra_store.invokeStatic(store.clj:31) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.store$cassandra_store.invoke(store.clj:17) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.bucket$cassandra_bucket_store.invokeStatic(bucket.clj:91) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.bucket$cassandra_bucket_store.invoke(bucket.clj:75) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.lang.Var.invoke(Var.java:379) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$instantiate.invokeStatic(config.clj:90) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$instantiate.invoke(config.clj:85) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$get_instance.invokeStatic(config.clj:98) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$get_instance.invoke(config.clj:93) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.core$apply.invokeStatic(core.clj:648) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.core$update_in.invokeStatic(core.clj:5950) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.core$update_in.doInvoke(core.clj:5939) ~[pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:467) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$init.invokeStatic(config.clj:169) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.config$init.invoke(config.clj:152) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos$_main.invokeStatic(pithos.clj:73) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos$_main.doInvoke(pithos.clj:57) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at clojure.lang.RestFn.applyTo(RestFn.java:137) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
	at io.pithos.main(Unknown Source) [pithos-0.7.6-SNAPSHOT-standalone.jar:na]
Disconnected from the target VM, address: '127.0.0.1:36015', transport: 'socket'
`

This because alia expects properties named "user/password", but store sets propeties username/password on the auth object. I'll submit a PR.

**Comment by federicoboerr** [comment]
Hi @pyr this change (https://github.com/exoscale/pithos/commit/7ea62bc32281f81fb86745c033f3d5237cb8ef93) does not seem to be included in any release.
Are you planning to release a new version (0.7.6)?
