### ISSUE TITLE
 403 (SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by InformatiQ** [exoscale/pithos#115]
using the examples provided I am unable to access pithos with s3cmd.
i receive this error

> ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

on pithos side i get this
```
INFO [2016-10-11 14:09:26,248] qtp1608757336-50 - io.pithos.sig will throw because of failed signature!
DEBUG [2016-10-11 14:09:26,257] qtp1608757336-50 - io.pithos.sig got exception during signing
java.lang.NullPointerException: null
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301) ~[pithos-0.7.5-standalone.jar:na]
        at io.pithos.sig$sign_string.invoke(sig.clj:41) ~[pithos-0.7.5-standalone.jar:na]
        at io.pithos.sig$sign_request.invoke(sig.clj:49) ~[pithos-0.7.5-standalone.jar:na]
        at io.pithos.sig$validate$fn__10177.invoke(sig.clj:93) ~[pithos-0.7.5-standalone.jar:na]
        at io.pithos.sig$validate.invoke(sig.clj:93) ~[pithos-0.7.5-standalone.jar:na]
        at io.pithos.request$authenticate.invoke(request.clj:231) [pithos-0.7.5-standalone.jar:na]
        at io.pithos.request$prepare.invoke(request.clj:269) [pithos-0.7.5-standalone.jar:na]
        at io.pithos.request$safe_prepare.invoke(request.clj:275) [pithos-0.7.5-standalone.jar:na]
        at io.pithos.api$executor$fn__12885.invoke(api.clj:20) [pithos-0.7.5-standalone.jar:na]
        at qbits.jet.server$make_handler$fn__8876.invoke(server.clj:70) [pithos-0.7.5-standalone.jar:na]
        at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.server.Server.handle(Server.java:497) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [pithos-0.7.5-standalone.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [pithos-0.7.5-standalone.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
DEBUG [2016-10-11 14:09:26,258] qtp1608757336-50 - io.pithos.sig string-to-sign:  GET
```

i have verified the key and secrets. i am using a local instance

```yaml
service:
  host: 0.0.0.0
  port: 8080
options:
  service-uri: s3.execbox.local
  default-region: 'CH-GV1'

keystore:
  key:
    AKIAIOSFODNN7EXAMPLE:
      master: true
      tenant: test@execbox.local
      secret: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'

bucketstore:
  default-region: 'CH-GV1'
  cluster:
    - cas1
    - cas2
  keyspace: 'test'

regions:
  CH-GV1:
    metastore:
      cluster:
        - cas1
        - cas2
      keyspace: 'test'
    storage-classes:
      standard:
        cluster:
          - cas1
          - cas2
        keyspace: 'test'
        max-chunk: '128k'
        max-block-chunks: 1024
```

s3.execbox.local is resolvable on that box

```
[default]
access_key = 'AKIAIOSFODNN7EXAMPLE'
bucket_location = CH-GV1
secret_key = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
signature_v2 = True
use_https = False
host_base = s3.execbox.local:8080
host_bucket = %(bucket)s.s3.execbox.local
#proxy_host = localhost
#proxy_port = 8080
```

with or without th eproxy lines i get the same error.

any pointers or ideas where to look?

thanks

**Comment by brutasse** [comment]
Your keystore config has a typo: keystore -> "keys" (plural).

http://pithos.io/quickstart.html#minimal-configuration

**Comment by InformatiQ** [comment]
thanks a lot for the quick help
