### ISSUE TITLE
removing acl on bucket fails

### ISSUE THREAD

**Issue by InformatiQ** [exoscale/pithos#120]
```
[rhanna@execbox ~]$ s3cmd --acl-revoke=read:toto  s3://user2
localhost:8080

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd  setacl --acl-revoke=read:toto s3://user2
Problem: AttributeError: 'NoneType' object has no attribute 'lower'
S3cmd:   1.6.1
python:   2.7.12 (default, Sep 29 2016, 13:30:34)
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1812, in cmd_setacl
    update_acl(s3, uri)
  File "/usr/bin/s3cmd", line 2427, in update_acl
    acl.revoke(**revoke)
  File "/usr/lib/python2.7/site-packages/S3/ACL.py", line 186, in revoke
    self.grantees = [g for g in self.grantees if not ((g.display_name.lower() == name and g.permission.upper() == permission)\
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by brutasse** [comment]
Can you run the same call with the `--debug` s3cmd flag? It'd help to have full HTTP requests and responses.

**Comment by InformatiQ** [comment]
```
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '.s3cfg2'
DEBUG: ConfigParser: host_base->s3.execbox.local:8080
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.execbox.local
DEBUG: ConfigParser: access_key->CK...17_chars...8
DEBUG: ConfigParser: secret_key->DI...37_chars...T
DEBUG: ConfigParser: use_https->False
DEBUG: ConfigParser: signature_v2->True
DEBUG: ConfigParser: proxy_host->localhost
DEBUG: ConfigParser: proxy_port->8080
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'setacl' using ANSI_X3.4-1968
DEBUG: Unicodising 's3://user2' using ANSI_X3.4-1968
DEBUG: Command: setacl
INFO: Setting bucket-level ACL for s3://user2/
DEBUG: CreateRequest: resource[uri]=/?acl
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 20 Oct 2016 12:14:34 +0000\n/user2/?acl'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(user2): user2.s3.execbox.local
DEBUG: ConnMan.get(): creating new connection: proxy://localhost:8080
DEBUG: proxied HTTPConnection(localhost, 8080)
localhost:8080
DEBUG: get_hostname(user2): user2.s3.execbox.local
DEBUG: format_uri(): http://user2.s3.execbox.local/?acl
DEBUG: Sending request method_string='GET', uri='http://user2.s3.execbox.local/?acl', headers={'Authorization': 'AWS CKI0J8AZUCW7GXS1GZK8:3k36EAWbSbdiMwbZCl53M7Pt0kk=', 'x-amz-date': 'Thu, 20 Oct 2016 12:14:34 +0
000'}, body=(0 bytes)
DEBUG: Response: {'status': 200, 'headers': {'x-amz-id-2': 'f3ccdccc-b145-4157-9a14-dc27285863a4', 'transfer-encoding': 'chunked', 'x-amz-request-id': 'f3ccdccc-b145-4157-9a14-dc27285863a4', 'content-type': 'appl
ication/xml', 'server': 'Pithos'}, 'reason': 'OK', 'data': '<?xml version="1.0" encoding="UTF-8"?><AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>foo</ID><DisplayName>bar</DisplayN
ame></Owner><AccessControlList><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>toto</ID><DisplayName></DisplayName></Grantee><Permission>READ</Permission></Grant
><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>user2</ID><DisplayName></DisplayName></Grantee><Permission>FULL_CONTROL</Permission></Grant><Grant><Grantee xmln
s:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>toto</ID><DisplayName></DisplayName></Grantee><Permission>WRITE</Permission></Grant></AccessControlList></AccessControlPolicy>'}
DEBUG: ConnMan.put(): closing proxy connection (keep-alive not yet supported)
DEBUG: acl: s3://user2/ - [Grantee("ID", "toto", "READ"), Grantee("ID", "user2", "FULL_CONTROL"), Grantee("ID", "toto", "WRITE")]
DEBUG: Unicodising '/usr/bin/s3cmd' using ANSI_X3.4-1968
DEBUG: Unicodising '-c' using ANSI_X3.4-1968
DEBUG: Unicodising '.s3cfg2' using ANSI_X3.4-1968
DEBUG: Unicodising 'setacl' using ANSI_X3.4-1968
DEBUG: Unicodising '--acl-revoke=read:toto' using ANSI_X3.4-1968
DEBUG: Unicodising 's3://user2' using ANSI_X3.4-1968
DEBUG: Unicodising '--debug' using ANSI_X3.4-1968
Invoked as: /usr/bin/s3cmd -c .s3cfg2 setacl --acl-revoke=read:toto s3://user2 --debug
Problem: AttributeError: 'NoneType' object has no attribute 'lower'
S3cmd:   1.6.1
python:   2.7.12 (default, Sep 29 2016, 13:30:34)
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1812, in cmd_setacl
    update_acl(s3, uri)
  File "/usr/bin/s3cmd", line 2427, in update_acl
    acl.revoke(**revoke)
  File "/usr/lib/python2.7/site-packages/S3/ACL.py", line 186, in revoke
    self.grantees = [g for g in self.grantees if not ((g.display_name.lower() == name and g.permission.upper() == permission)\
AttributeError: 'NoneType' object has no attribute 'lower'
```
