### ISSUE TITLE
SignatureDoesNotMatch during multipart upload

### ISSUE THREAD

**Issue by dsehrawa** [exoscale/pithos#151]
Hello, I tried to load a multipart mp4 file using s3cmd client. It happens only for multipart upload. I am getting below error at s3cmd for multipart upload:
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

And below error at pithos console:
DEBUG [2017-03-31 14:15:22,649] qtp1169324755-78 - io.pithos.request unhandled exception during request preparation
clojure.lang.ExceptionInfo: invalid request signature
	at clojure.core$ex_info.invoke(core.clj:4593) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.sig$validate.invoke(sig.clj:103) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.request$authenticate.invoke(request.clj:231) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.request$prepare.invoke(request.clj:269) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.request$safe_prepare.invoke(request.clj:275) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.api$executor$fn__12885.invoke(api.clj:20) [pithos-0.7.5-standalone.jar:na]
	at qbits.jet.server$make_handler$fn__8876.invoke(server.clj:70) [pithos-0.7.5-standalone.jar:na]
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [pithos-0.7.5-standalone.jar:na]

**Comment by brutasse** [comment]
Hello,

Did you force the use of v2 signature in `.s3cfg`? This can be done by setting `signature_v2 = True`.
