### ISSUE TITLE
restarting docker fails because keyspace already exists in cassandra

### ISSUE THREAD

**Issue by jdelamar** [exoscale/pithos#160]
Good day. I may be missing something, but is there a way to have pithos acknowledge that a schema already exists in cassandra on startup?

Right now, I am using docker swarm and deploying Pithos + Cassandra + other apps. On first deploy, everything works fine. But if I redeploy my services and pithos is restarted, it continuously fails with the following exception:

The stacktrace is quite verbose. I have attached it to this issue, but here are the relevant parts. I have quickly look at the code and haven't found where we would add "IF NOT EXISTS" when creating the cassandra tables. I may have missed it though, but this is required if we bootstrap the schema everytime we start.

Is this a known issue?
[pithos_cassandra_ks_exists_exception.txt](https://github.com/exoscale/pithos/files/1200955/pithos_cassandra_ks_exists_exception.txt)

```
druid_pithos.1.r2zxixyl0i96@debian-leader    | ERROR [2017-08-04 15:57:43,214] main - io.pithos.schema cannot create schema
druid_pithos.1.r2zxixyl0i96@debian-leader    | clojure.lang.ExceptionInfo: Query execution failed

//...

druid_pithos.1.7c14y8cb98qa@debian-leader    | Caused by: com.datastax.driver.core.exceptions.AlreadyExistsException: Table storage.bucket already exists
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:197)
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at qbits.alia$ex__GT_ex_info.invokeStatic(alia.clj:205)
druid_pithos.1.3tokwf0q38p2@debian-leader    | 	at io.pithos$_main.doInvoke(pithos.clj:57)
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.exceptions.AlreadyExistsException.copy(AlreadyExistsException.java:130)
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.Responses$Error.asException(Responses.java:140)
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at qbits.alia$ex__GT_ex_info.invoke(alia.clj:197)
druid_pithos.1.3tokwf0q38p2@debian-leader    | 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
druid_pithos.1.3tokwf0q38p2@debian-leader    | 	at io.pithos.main(Unknown Source)
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at qbits.alia$execute.invokeStatic(alia.clj:375)
druid_pithos.1.3tokwf0q38p2@debian-leader    | Caused by: com.datastax.driver.core.exceptions.AlreadyExistsException: Table storage.bucket already exists
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177)
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at qbits.alia$execute.invoke(alia.clj:316)
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46)
druid_pithos.1.7c14y8cb98qa@debian-leader    | 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:797)
druid_pithos.1.r2zxixyl0i96@debian-leader    | 	at io.pithos.bucket$cassandra_bucket_store$write_BANG___10977.invoke(bucket.clj:94)
druid_pithos.1.3tokwf0q38p2@debian-leader    | 	at com.datastax.driver.core.exceptions.AlreadyExistsException.copy(AlreadyExistsException.java:130)

```

**Comment by Jc2k** [comment]
Hey - it sounds like we are doing something similar. Did you get anywhere with this?

The schema stuff only needs to be run once. It's just a step in the docker-entrypoint.sh. You could comment it out. I've made it a non fatal error for now in my dev env, but will probably remove it and run it manually once on initial deployment.

I'll put together a pr with some of my docker bits - it would be great to compare notes - esp your cassandra swarm setup - have you got scaling cracked?

**Comment by jdelamar** [comment]
Yeah. I was going to do the same. I don't know Clojure yet, so I am slooow reading and experimenting with it. Your PR is going to be appreciated :)

I haven't tried cassandra scaling with the newer docker swarm. Done it outside of swarm numerous times, though. This is what I was planning to do, using docker-compose.yml v3 (docker 1.13 / 17.06)

1. Cassandra requires at least 1 seeds, better with two. I need a way to get the seed of the first two nodes. I haven't found a sexy way of doing this, so right now I specify it via env variable. I "know" the cassandra hostnames (cassandra.1, cassandra.2, etc...), so I make sure that every new cassandra nodes scaled has at least the first two nodes in the setup specify as env variable. 

2. The cassandra container sets these values in their seed value in cassandra.yaml. So, every new node (swarm services) will reach out to at least one of the seed to learn topology. Wonderful.

2a. The pithos container could piggy back off those seeds as well.

3. That will most likely break horribly when the Docker swarm scheduling system decides to schedule  one of my cassandra on a different server after failure, but I plan on dealing with this by not allowing any two cassandra to be deployed on the same hosts. Ideally, cassandra.2 deployed on host.2 should "stick" to that host. AFAIK, there is no way to tell docker that in docker 1.13, but I could be wrong.

3a. Worse come to worse, I may need to spell out my deployment in docker-compose.yml, with 5 cassandra nodes on 5 hosts using 5 different labels. That would suck. But like often does...

4. After scaling, we need to run nodetool commands to make data sift through. nodetool repair may be needed. We could trigger that on docker scale operation (if we could hook to that). Right now I am using ansible behind the scene and was planning to use that.

I plan on trying this in the upcoming two weeks. Does that make sense to you? Did you start playing with this?

**Comment by Jc2k** [comment]
I'm a bit of a cassandra noob tbh, but makes sense.

So far I did a 6 node test setup where seeds was populated using the dns stuff in swarm - it worked but I think I read it's bad to have too many seeds? (As in https://github.com/docker-library/cassandra/issues/94#issuecomment-311839953).

For that set up I went with global placement with constraints rather than replicated. Every physical host I tag cassandra gets one and only one instance of the container.

I haven't looked yet but I'm kind of hoping there is a version of 'docker events' for swarm so I can write a little 'on scale' daemon.

**Comment by jdelamar** [comment]
Correct, you really only need two seeds per datacenter. I will let you know if my progress

_Sent from my Samsung SM-G950W using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Antauri** [comment]
Updating to hyat 4.0.1 and alia 4.2.1 and adding an (if-exists false) to all the create-* statements fixes the issue as the queries become idempotent (IF NOT EXISTS). We're using Docker for deployment so we had that issue also :) ... initially we though of importing the schema by ourselves, but since the auto-generation of the schema for each storage-class is so nice, we figured fixing the code is easier and it was.

I'll send-off an PR for a fix for this also if we can get v4 signatures merged, even in their raw/crude form (which works for our needs with the standard tools and SDKs). Sadly, the project hasn't been getting much love, although some of us adopted it as a solution for simple blobstorage with very good HA (C* backed).

**Comment by pyr** [comment]
Hi @Antauri,

I'll look at the hayt PR and the V4 signature code shortly. Sorry for the delay.
We're working on open-sourcing our next iteration of pithos which offers much better protocol support (and v4 signatures in all their awful variations) as well as much better throughput and latency, which is why our progress on this project has been slow.

**Comment by yhilem** [comment]
Hi Pierre-Yves,
This is good news about the features of this new version.
Can you tell us when can we expect access to this version?

Regards
Youcef HILEM
