### ISSUE TITLE
java.lang.NullPointerException (caught exception during operation)

### ISSUE THREAD

**Issue by AlvaroBro** [exoscale/pithos#168]
Hi, 

I'm trying out Pithos 0.7.5 and I'm getting this error. I'm unable to debug why.
I've been able to upload files perfectly using "S3 Browser" app, but I'm failing to do so using a custom app that does work well against AWS S3.

Here is the log:

```
DEBUG [2018-02-01 13:41:46,478] cluster3-nio-worker-1 - com.datastax.driver.core.Connection Connection[localhost/127.0.0.1:9042-1, inFlight=0, closed=false] heartbeat query succeeded
DEBUG [2018-02-01 13:42:08,204] cluster1-nio-worker-1 - com.datastax.driver.core.Connection Connection[localhost/127.0.0.1:9042-2, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
DEBUG [2018-02-01 13:42:08,205] cluster1-nio-worker-1 - com.datastax.driver.core.Connection Connection[localhost/127.0.0.1:9042-2, inFlight=0, closed=false] heartbeat query succeeded
DEBUG [2018-02-01 13:42:12,466] qtp837923432-35-acceptor-0@5eee3da9-ServerConnector@3199a202{HTTP/1.1}{127.0.0.1:8080} - org.eclipse.jetty.io.SelectorManager Queued change org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept@5daa16bf
DEBUG [2018-02-01 13:42:12,466] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Selector loop woken up from select, 0/0 selected
DEBUG [2018-02-01 13:42:12,466] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Running change org.eclipse.jetty.io.SelectorManager$ManagedSelector$Accept@5daa16bf
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.AbstractEndPoint onOpen SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,-,-,1/200000,null}{io=0,kio=0,kro=0}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.IdleTimeout SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,-,-,1/200000,null}{io=0,kio=0,kro=0} idle timeout check, elapsed: 1 ms, remaining: 199999 ms
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.server.HttpChannel new HttpChannelOverHttp@1d78d4ad{r=0,c=false,a=IDLE,uri=-} -> SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,-,-,1/200000,null}{io=0,kio=0,kro=0},null,HttpChannelState@1d7c3b05{s=IDLE i=true a=null}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.server.HttpConnection New HTTP Connection HttpConnection@99d57e3{IDLE}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.AbstractConnection onOpen HttpConnection@99d57e3{IDLE}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.AbstractConnection fillInterested HttpConnection@99d57e3{IDLE}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.AbstractConnection IDLE-->FILL_INTERESTED HttpConnection@99d57e3{FILL_INTERESTED}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectChannelEndPoint Local interests updating 0 -> 1 for SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,R,-,0/200000,HttpConnection}{io=1,kio=0,kro=0}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@6408d5b8
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectChannelEndPoint Key interests updated 0 -> 1 on SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,R,-,0/200000,HttpConnection}{io=1,kio=1,kro=0}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Created SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,R,-,0/200000,HttpConnection}{io=1,kio=1,kro=0}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Selector loop waiting on select
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Selector loop woken up from select, 1/1 selected
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectChannelEndPoint Key interests updated 1 -> 0 on SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,R,-,0/200000,HttpConnection}{io=1,kio=0,kro=1}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectChannelEndPoint Local interests updating 1 -> 0 for SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,R,-,0/200000,HttpConnection}{io=0,kio=0,kro=1}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Running change org.eclipse.jetty.io.SelectChannelEndPoint$1@6408d5b8
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.AbstractConnection FILL_INTERESTED-->FILLING HttpConnection@99d57e3{FILLING}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-34-selector-ServerConnectorManager@3b347439/0 - org.eclipse.jetty.io.SelectorManager Selector loop waiting on select
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.server.HttpConnection HttpConnection@99d57e3{FILLING} onFillable HttpChannelState@1d7c3b05{s=IDLE i=true a=null}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.io.ChannelEndPoint filled 1745 SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,-,-,0/200000,HttpConnection}{io=0,kio=0,kro=1}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser parseNext s=START HeapByteBuffer@62e4e2d4[p=0,l=1745,c=65536,r=1745]={<<<POST /bkt3days/ H...15F70E40D2B--\r\n>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser START --> SPACE1
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser SPACE1 --> URI
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser URI --> SPACE2
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser SPACE2 --> REQUEST_VERSION
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser REQUEST_VERSION --> HEADER
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,467] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> HEADER_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_VALUE --> HEADER_IN_VALUE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER_IN_VALUE --> HEADER
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.http.HttpParser HEADER --> CONTENT
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@1d78d4ad{r=1,c=false,a=IDLE,uri=-} handle enter
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpChannelState HttpChannelState@1d7c3b05{s=IDLE i=true a=null} handling IDLE
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@1d78d4ad{r=1,c=false,a=DISPATCHED,uri=/bkt3days/} action REQUEST_DISPATCH
DEBUG [2018-02-01 13:42:12,468] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.Server REQUEST POST /bkt3days/ on HttpChannelOverHttp@1d78d4ad{r=1,c=false,a=DISPATCHED,uri=/bkt3days/}
DEBUG [2018-02-01 13:42:12,471] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.http.HttpParser parseNext s=CONTENT HeapByteBuffer@62e4e2d4[p=306,l=1745,c=65536,r=1439]={POST /bkt3days/ H...ip, deflate\r\n\r\n<<<--Boundary+FA6211...15F70E40D2B--\r\n>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
DEBUG [2018-02-01 13:42:12,471] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpChannel HttpChannelOverHttp@1d78d4ad{r=1,c=false,a=DISPATCHED,uri=/bkt3days/} content java.nio.HeapByteBufferR[pos=306 lim=1745 cap=65536]
DEBUG [2018-02-01 13:42:12,472] qtp837923432-40 - /bkt3days/ - io.pithos.operations handling operation:  :post-bucket
ERROR [2018-02-01 13:42:12,475] qtp837923432-40 - /bkt3days/ - io.pithos.operations caught exception during operation
java.lang.NullPointerException: null
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:26) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.operations$validate_post_policy.invoke(operations.clj:500) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.operations$post_bucket.invoke(operations.clj:516) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.operations$dispatch$fn__10933.invoke(operations.clj:884) ~[pithos-0.7.5-standalone.jar:na]
	at io.pithos.operations$dispatch.invoke(operations.clj:880) [pithos-0.7.5-standalone.jar:na]
	at io.pithos.api$executor$fn__12885.invoke(api.clj:21) [pithos-0.7.5-standalone.jar:na]
	at qbits.jet.server$make_handler$fn__8876.invoke(server.clj:70) [pithos-0.7.5-standalone.jar:na]
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [pithos-0.7.5-standalone.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [pithos-0.7.5-standalone.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
DEBUG [2018-02-01 13:42:12,476] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpConnection org.eclipse.jetty.server.HttpConnection$SendCallback@5d3de558[PROCESSING][i=ResponseInfo{HTTP/1.0 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@d17609a] generate: NEED_HEADER (null,[p=0,l=234,c=32768,r=234],false)@START
DEBUG [2018-02-01 13:42:12,476] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpConnection org.eclipse.jetty.server.HttpConnection$SendCallback@5d3de558[PROCESSING][i=ResponseInfo{HTTP/1.0 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@d17609a] generate: FLUSH ([p=0,l=182,c=8192,r=182],[p=0,l=234,c=32768,r=234],false)@COMMITTED
DEBUG [2018-02-01 13:42:12,476] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.io.WriteFlusher write: WriteFlusher@4ea7ecc0{IDLE} [HeapByteBuffer@49338a7d[p=0,l=182,c=8192,r=182]={<<<HTTP/1.1 500 Serv...197cbad69ab\r\n\r\n>>>SNAPSHOT)\r\n\r\n\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00},HeapByteBuffer@35c5e60e[p=0,l=234,c=32768,r=234]={<<<<?xml version="1....HostId></Error>>>>1087</HostId><Fie...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}]
DEBUG [2018-02-01 13:42:12,476] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.io.WriteFlusher update WriteFlusher@4ea7ecc0{WRITING}:IDLE-->WRITING
DEBUG [2018-02-01 13:42:12,476] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.io.ChannelEndPoint flushed 416 SelectChannelEndPoint@4ae4f383{/127.0.0.1:42370<->8080,Open,in,out,-,W,9/200000,HttpConnection}{io=0,kio=0,kro=1}
DEBUG [2018-02-01 13:42:12,477] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.io.WriteFlusher update WriteFlusher@4ea7ecc0{IDLE}:WRITING-->IDLE
DEBUG [2018-02-01 13:42:12,477] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.HttpConnection org.eclipse.jetty.server.HttpConnection$SendCallback@5d3de558[PROCESSING][i=ResponseInfo{HTTP/1.0 500 null,-1,false},cb=org.eclipse.jetty.server.HttpChannel$CommitCallback@d17609a] generate: DONE ([p=182,l=182,c=8192,r=0],[p=234,l=234,c=32768,r=0],false)@COMMITTED
DEBUG [2018-02-01 13:42:12,477] qtp837923432-40 - /bkt3days/ - org.eclipse.jetty.server.Server RESPONSE /bkt3days/  500 handled=true
```

Line 500 of operations.clj is:

`"starts-with" (.startsWith value expected))`

inside function:

```
(defn validate-post-policy
  [req {:keys [expiration conditions]} params]
  (let [array-conds (remove map? conditions)
        map-conds   (filter map? conditions)]
    (when (and expiration (after? (now) (iso8601->date expiration)))
      (debug "expired request per policy" (pr-str {:expires expiration}))
      (throw (ex-info "expired request"
                      {:type :expired-request
                       :status-code 403
                       :request req
                       :expires expiration})))
    (doseq [condition map-conds
            :let [field    (-> condition keys first)
                  expected (-> condition vals first)
                  value (get params field)]]
      (when-not (= expected value)
        (debug "upload policy violation"
               (pr-str {:condition condition :value value}))
        (throw (ex-info "request does not honor policy"
                        {:type :upload-policy-violation
                         :status-code 403
                         :request req
                         :field field
                         :value value
                         :expected expected}))))
    (doseq [[check-type field expected] array-conds
            :let [field    (-> field (.substring 1) lower-case keyword)
                  value    (get params field)]]
      (when-not (case check-type
                  "eq" (= expected value)
                  "starts-with" (.startsWith value expected))
        (debug "upload policy violation"
               (pr-str {:condition [check-type field expected]
                        :value value}))
        (throw (ex-info "request does not honor policy"
                        {:type :upload-policy-violation
                         :status-code 403
                         :request req
                         :field field
                         :value value
                         :expected (format "%s(%s)" check-type value)})))))
  true)
```

What are the possible causes for a null pointer exception in that line?

Thank you in advance!!

**Comment by AlvaroBro** [comment]
I found the cause:

If you set a conditions in "conditions" under the "policy" field of the credentials, such as, for example:

```
"conditions": [
...
["starts-with", "$Content-Type", ""],
...
]
```

Note that the problem seems to be the fact that we are specifying an empty string. That is accepted in Amazon S3, but makes Pithos throw that exception.

You will get that NullPointerException
