### ISSUE TITLE
Exception in Pithos logs for ranged GET requests

### ISSUE THREAD

**Issue by numbat** [exoscale/pithos#57]
I've been doing range request tests with files of varying sizes and am encountering an error in the retreival of the last block in non-trivially small files - the logs below show a test with a 128k file created with mkfile, which I then put into S3 via s3cmd (though this issue manifests with files with any binary data):

```
$ mkfile 128k 128kb.file

$ s3cmd -c s3cfg put 128kb.file s3://bucket-1
128kb.file -> s3://bucket-1/128kb.file  [1 of 1]
 131072 of 131072   100% in    0s  1417.06 kB/s  done

$ s3cmd -c s3cfg la
2015-03-24 23:26    131072   s3://bucket-1/128kb.file
```

Testing with the AWS SDK and JetS3t, I observe the following error in the last chunk (two ranged requests, the first for 0-131063 and the second for 131064-131071:

```
DEBUG [2015-03-25 11:32:39,118] qtp2030716684-168 - io.pithos.request - request:  {:ssl-client-cert nil, :remote-addr "127.0.0.1", :headers {"date" "Wed, 25 Mar 2015 00:32:38 GMT", "range" "bytes=0-131063", "host" "127.0.0.1:8888", "user-agent" "JetS3t/0.9.3 (Mac OS X/10.10.2; x86_64; en; JVM 1.7.0_51)", "connection" "Keep-Alive", "authorization" "AWS ..."}, :server-port 8888, :content-length nil, :content-type nil, :character-encoding nil, :uri "/bucket-1/128kb.file", :server-name "127.0.0.1", :query-string nil, :body #<HttpInputOverHTTP HttpInputOverHTTP@4e12ec07>, :scheme :http, :request-method :get}
DEBUG [2015-03-25 11:32:39,123] qtp2030716684-168 - io.pithos.operations - handling operation:  :get-object
DEBUG [2015-03-25 11:32:39,141] qtp2030716684-168 - io.pithos.operations - will stream  #uuid "5b2508fb-3380-4f21-b87b-20a5969c9683" #uuid "34ed9d50-d27d-11e4-8f75-013f6658818a"
DEBUG [2015-03-25 11:32:39,142] clojure-agent-send-off-pool-1 - io.pithos.stream - got range:  0 131064
DEBUG [2015-03-25 11:32:39,148] clojure-agent-send-off-pool-1 - io.pithos.stream - got  1 blocks
DEBUG [2015-03-25 11:32:39,148] clojure-agent-send-off-pool-1 - io.pithos.stream - found block  0
DEBUG [2015-03-25 11:32:39,153] clojure-agent-send-off-pool-1 - io.pithos.stream - got  17  chunks
DEBUG [2015-03-25 11:32:39,163] clojure-agent-send-off-pool-1 - io.pithos.stream - closing after read
DEBUG [2015-03-25 11:32:39,215] qtp2030716684-169 - io.pithos.request - request:  {:ssl-client-cert nil, :remote-addr "127.0.0.1", :headers {"date" "Wed, 25 Mar 2015 00:32:39 GMT", "range" "bytes=131064-131071", "host" "127.0.0.1:8888", "user-agent" "JetS3t/0.9.3 (Mac OS X/10.10.2; x86_64; en; JVM 1.7.0_51)", "connection" "Keep-Alive", "authorization" "AWS ..."}, :server-port 8888, :content-length nil, :content-type nil, :character-encoding nil, :uri "/bucket-1/128kb.file", :server-name "127.0.0.1", :query-string nil, :body #<HttpInputOverHTTP HttpInputOverHTTP@4e12ec07>, :scheme :http, :request-method :get}
DEBUG [2015-03-25 11:32:39,220] qtp2030716684-169 - io.pithos.operations - handling operation:  :get-object
DEBUG [2015-03-25 11:32:39,233] qtp2030716684-169 - io.pithos.operations - will stream  #uuid "5b2508fb-3380-4f21-b87b-20a5969c9683" #uuid "34ed9d50-d27d-11e4-8f75-013f6658818a"
DEBUG [2015-03-25 11:32:39,233] clojure-agent-send-off-pool-1 - io.pithos.stream - got range:  131064 131072
DEBUG [2015-03-25 11:32:39,235] clojure-agent-send-off-pool-1 - io.pithos.stream - got  1 blocks
DEBUG [2015-03-25 11:32:39,236] clojure-agent-send-off-pool-1 - io.pithos.stream - found block  0
DEBUG [2015-03-25 11:32:39,240] clojure-agent-send-off-pool-1 - io.pithos.stream - got  17  chunks
ERROR [2015-03-25 11:32:40,241] clojure-agent-send-off-pool-1 - io.pithos.stream - error during read
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:268)
	at java.io.PipedInputStream.receive(PipedInputStream.java:231)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at io.pithos.stream$stream_to$fn__9894.invoke(stream.clj:48)
	at io.pithos.stream$stream_to.invoke(stream.clj:31)
	at io.pithos.operations$get_object$fn__10276.invoke(operations.clj:401)
	at clojure.core$binding_conveyor_fn$fn__4425.invoke(core.clj:1912)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
DEBUG [2015-03-25 11:32:40,242] clojure-agent-send-off-pool-1 - io.pithos.stream - closing after read
```

In my test script, I see the following output when the second ranged request is made. Here is the output from JetS3t:
```
Exception in thread "main" org.jets3t.service.S3ServiceException: Request Error: null
	at org.jets3t.service.S3Service.getObject(S3Service.java:2678)
	at andrew.snippets.JetS3tRangeGetTest.main(JetS3tRangeGetTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:326)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRequest(RestStorageService.java:277)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1090)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.performRestGet(RestStorageService.java:1062)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2253)
	at org.jets3t.service.impl.rest.httpclient.RestStorageService.getObjectImpl(RestStorageService.java:2190)
	at org.jets3t.service.StorageService.getObject(StorageService.java:1167)
	at org.jets3t.service.S3Service.getObject(S3Service.java:2674)
	... 6 more
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	... 16 more
```

And the same test but using Amazon's AWS SDK (1.9.0):
```
Mar 25, 2015 11:51:31 AM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: null
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:867)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3655)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1132)
	at andrew.snippets.AwsSdkRangeGetTest.main(AwsSdkRangeGetTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:66)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	... 13 more
```

This seems to also manifest when I do a ranged request that does not start from the 0th byte. I don't understand exactly what is happening our how to interpret the logs - is Pithos closing the stream to Cassandra once it has the bytes required to fulfil the range request?

If I do a non-ranged request, the file downloads correctly. My storage settings are below, otherwise my other settings are as per the defaults in the Quickstart:

```
regions:
  CH-GV1:
    metastore:
      cluster: 'localhost'
      keyspace: 'storage'
    storage-classes:
      standard:
        cluster: 'localhost'
        keyspace: 'storage'
        max-chunk: '1024k'
        max-block-chunks: 1024
```

**Comment by pyr** [comment]
This is now fixed in master.
