### ISSUE TITLE
Docker Registry fails to sign requests, no matter what

### ISSUE THREAD

**Issue by timcharper** [exoscale/pithos#86]
I've set up pithos and have s3cmd working for uploads, downloads, etc. However, no matter what I do, I cannot get docker registry to talk to it without giving a signature failed error.

Working `~/.s3cfg`:

```
[default]
host_base = pithos.marathon.mesos
host_bucket = pithos.marathon.mesos
access_key = BUNKHOUSEREGISTRY000
secret_key = vJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
signature_v2 = True
use_https = False
```

Pithos cfg:

```
#
## pithos main configuration
## =========================
#
# This file contains the following sections
#   - service
#   - logging
#   - options
#   - keystore
#   - bucketstore
#   - regions


## service configuration
## ---------------------
#
# indicates
service:
  host: 0.0.0.0
  port: 80


## logging configuration
## ---------------------
logging:
  level: info
  console: true
# overrides:
#   io.exo.pithos: debug


## global options
## --------------
options:
  service-uri: pithos.marathon.mesos
  reporting: true
  server-side-encryption: false
  multipart-upload: true
  masterkey-provisioning: true
  masterkey-access: true
  default-region: us-west-1

## keystore configuration
## ----------------------
#
# Keystores associate an access key with
# an organization and secret key.
#
# They may offer provisioning capacities with the
# masterkey. The default provider relies on keys
# being defined inline.
keystore:
  keys:
    BUNKHOUSEREGISTRY000:
      master: true
      tenant: 'user@email.com'
      secret: 'vJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'

## bucketstore configuration
## -------------------------
#
# The bucketstore is ring global and contains information
# on bucket location and global parameters.
#
# Its primary aim is to hold bucket location and ownership
# information.
#
# The default provider relies on cassandra.
bucketstore:
  default-region: 'us-west-1'
  cluster: 'cass-obj.weave.local'
  keyspace: storage
  repfactor: 3


## regions
## -------
#
# Regions are composed of a metastore and an arbitrary number
# of named storage classes which depend on a blobstore.
#
# The metastore holds metadata for the full region, as well as
# object storage-class placement information.
#
# The default implementation of both metastore and blobstore
# rely on cassandra.
#
regions:
  sw-ax:
    metastore:
      cluster: 'cass-obj.weave.local'
      keyspace: storage
      repfactor: 3
    storage-classes:
      standard:
        cluster: 'cass-obj.weave.local'
        keyspace: storage
        max-chunk: 128k
        max-block-chunks: 1024
        repfactor: 3
```

Docker config:

```
     2	log:
     3	  level: debug
     4	  formatter: text
     5	  fields:
     6	    service: registry
     7	    environment: staging
     8	storage:
     9	  cache:
    10	    blobdescriptor: inmemory
    11	  s3:
    12	    accesskey: BUNKHOUSEREGISTRY000
    13	    secretkey: vJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    14	    region: us-west-1
    15	    regionendpoint: pithos.marathon.mesos
    16	    bucket: docker-registry
    17	    encrypt: false
    18	    secure: false
    19	    v4auth: false
    20	    chunksize: 5242880
    21	    rootdirectory: /s3/object/name/prefix
    22	http:
    23	  addr: :80
    24	  headers:
    25	    X-Content-Type-Options: [nosniff]
    26	health:
    27	  storagedriver:
    28	    enabled: true
    29	    interval: 10s
    30	    threshold: 3
```

Error reported by pithos:

```
/docker-registry
DEBUG [2016-04-22 11:47:31,829] qtp2032752946-265 - io.pithos.request - unhandled exception during request preparation
clojure.lang.ExceptionInfo: invalid request signature {:type :signature-does-not-match, :status-code 403, :request {:sign-uri "/docker-registry", :ssl-client-cert nil, :reqid #uuid "0193ff5c-b4e0-4b65-8d15-be3d1ade54d6", :remote-addr "10.43.128.7", :operation :get-bucket, :params {:delimiter "/", :max-keys "1000", :prefix "s3/object/name/prefix/"}, :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0x2f2f61d3 "clojure.core.async.impl.channels.ManyToManyChannel@2f2f61d3"], :headers {"user-agent" "aws-sdk-go/1.1.0 (go1.6.1; linux; amd64)", "authorization" "AWS4-HMAC-SHA256 Credential=BUNKHOUSEREGISTRY000/20160422/us-west-1/s3/aws4_request, SignedHeaders=host;x-amz-date, Signature=1ce26f0111cd86de57d79e57513b49482126bcfd4cdf117ad480c34e65c3fe2e", "x-amz-date" "20160422T114731Z", "host" "pithos.marathon.mesos", "x-amz-content-sha256" "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855", "accept-encoding" "gzip"}, :server-port 80, :servlet-request #object[org.eclipse.jetty.server.Request 0x121fb432 "(GET http://pithos.marathon.mesos/docker-registry?delimiter=%2F&max-keys=1000&prefix=s3%2Fobject%2Fname%2Fprefix%2F)@304067634 org.eclipse.jetty.server.Request@121fb432"], :action-params #{}, :content-length nil, :content-type nil, :character-encoding nil, :action nil, :uri "/docker-registry", :server-name "pithos.marathon.mesos", :target :bucket, :query-string "delimiter=%2F&max-keys=1000&prefix=s3%2Fobject%2Fname%2Fprefix%2F", :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0x6c2efda5 "HttpInputOverHTTP@6c2efda5"], :scheme :http, :object nil, :request-method :get, :bucket "docker-registry"}, :expected {:failed true, :exception #error {
 :cause nil
 :via
 [{:type java.lang.NullPointerException
   :message nil
   :at [clojure.lang.Reflector invokeNoArgInstanceMember "Reflector.java" 301]}]
 :trace
 [[clojure.lang.Reflector invokeNoArgInstanceMember "Reflector.java" 301]
  [io.pithos.sig$sign_string invoke "sig.clj" 41]
  [io.pithos.sig$sign_request invoke "sig.clj" 49]
  [io.pithos.sig$validate$fn__8107 invoke "sig.clj" 91]
  [io.pithos.sig$validate invoke "sig.clj" 91]
  [io.pithos.request$authenticate invoke "request.clj" 223]
  [io.pithos.request$prepare invoke "request.clj" 261]
  [io.pithos.request$safe_prepare invoke "request.clj" 268]
  [io.pithos.api$executor$fn__12399 invoke "api.clj" 20]
  [qbits.jet.server$make_handler$fn__8819 invoke "server.clj" 70]
  [qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a handle nil -1]
  [org.eclipse.jetty.server.handler.HandlerList handle "HandlerList.java" 52]
  [org.eclipse.jetty.server.handler.HandlerWrapper handle "HandlerWrapper.java" 97]
  [org.eclipse.jetty.server.Server handle "Server.java" 497]
  [org.eclipse.jetty.server.HttpChannel handle "HttpChannel.java" 310]
  [org.eclipse.jetty.server.HttpConnection onFillable "HttpConnection.java" 257]
  [org.eclipse.jetty.io.AbstractConnection$2 run "AbstractConnection.java" 540]
  [org.eclipse.jetty.util.thread.QueuedThreadPool runJob "QueuedThreadPool.java" 635]
  [org.eclipse.jetty.util.thread.QueuedThreadPool$3 run "QueuedThreadPool.java" 555]
  [java.lang.Thread run "Thread.java" 745]]}}, :to-sign "GET\n\n\n\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20160422T114731Z\n/docker-registry"}
	at clojure.core$ex_info.invoke(core.clj:4591)
	at io.pithos.sig$validate.invoke(sig.clj:101)
	at io.pithos.request$authenticate.invoke(request.clj:223)
	at io.pithos.request$prepare.invoke(request.clj:261)
	at io.pithos.request$safe_prepare.invoke(request.clj:268)
	at io.pithos.api$executor$fn__12399.invoke(api.clj:20)
	at qbits.jet.server$make_handler$fn__8819.invoke(server.clj:70)
	at qbits.jet.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

Does anything look obvious?

**Comment by schu** [comment]
Hi @timcharper, unfortunately the default s3 driver (aws-sdk-go) in the registry doesn't support v2 authentication and Pithos doesn't support v4 authentication yet. Support to freely configure s3-compatible storage providers also is lacking behind (e.g. no way to configure non-aws regions, as you have noticed). Hopefully the situation will improve in the not so far future (docker/distribution#1389).

It's possible to do it by using the legacy s3goamz driver (also included with the registry) + a hotfix on top of docker/distribution to add a `Pithos` region and avoid an issue with empty delimiters. If you want, you can use my pithos tree as an example: https://github.com/schu/distribution/tree/pithos

**Comment by timcharper** [comment]
Thank you, @schu ! I'll give your fork a try.

**Comment by timcharper** [comment]
Bummer; I tried your fork, and it still didn't work. I had to add support for the `regionendpoint` parameter, my implementation of which can be seen by this diff:

```diff
diff --git a/registry/storage/driver/s3-goamz/s3.go b/registry/storage/driver/s3-goamz/
index feff1b7..b71be07 100644
--- a/registry/storage/driver/s3-goamz/s3.go
+++ b/registry/storage/driver/s3-goamz/s3.go
@@ -118,6 +118,11 @@ func FromParameters(parameters map[string]interface{}) (*Driver, e
        if region.Name == "" {
                return nil, fmt.Errorf("Invalid region provided: %v", region)
        }
+       regionendpoint := parameters["regionendpoint"]
+       if regionendpoint != nil {
+               region.S3Endpoint = fmt.Sprint(regionendpoint)
+               region.EC2Endpoint.Endpoint = region.S3Endpoint
+       }

        bucket := parameters["bucket"]
        if bucket == nil || fmt.Sprint(bucket) == "" {
```

Still getting the same signature failed issue ༼ ༎ຶ ෴ ༎ຶ༽

**Comment by timcharper** [comment]
but this really isn't an issue with Pithos.

**Comment by schu** [comment]
> Bummer; I tried your fork, and it still didn't work. I had to add support for the regionendpoint parameter

If you don't want to add a static region like I did (https://github.com/schu/distribution/blob/pithos/vendor/github.com/docker/goamz/aws/regions.go#L292-L294), that's the way to go. Maybe upstream would accept a patch, IIRC they have a similar option for the new driver.

With s3goamz you also need to address the delimiter issue though, then it should work. This are the three changes to `d.Bucket.List(...)` as seen here: https://github.com/schu/distribution/commit/7e8017b6ac5f9a0c759274ecd236988b3ae40432

**Comment by timcharper** [comment]
The diff I posted was on top of your fork, so it contained those changes already.

Here's the failed posting from the forked `distribution`:

```
DEBU[0080] s3goamz.List("/")                             environment=prod go.version=go1.6 instance.id=9f5a845f-b48e-4593-84cf-671b879129f7 service=registry trace.duration=20.414744ms trace.file=/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go trace.func=github.com/docker/distribution/registry/storage/driver/base.(*Base).List trace.id=767c664a-e57f-48e0-a303-11d61c500ba9 trace.line=150 version=v2.3.0-rc.1-248-g7e8017b.m
2016/04/25 15:26:05 Signature payload: "GET\n\n\nMon, 25 Apr 2016 15:26:05 UTC\n/docker-registry/"
2016/04/25 15:26:05 Signature: "Z5lfar1QrEnZZt9MYSWM7C6NLAE="
2016/04/25 15:26:05 Running S3 request: &s3.request{method:"GET", bucket:"docker-registry", path:"/docker-registry/", params:url.Values{"max-keys":[]string{"1000"}, "prefix":[]string{""}, "delimiter":[]string{"/"}, "marker":[]string{""}}, headers:http.Header{"Host":[]string{"pithos.marathon.mesos"}, "Date":[]string{"Mon, 25 Apr 2016 15:26:05 UTC"}, "Authorization":[]string{"AWS BUNKHOUSEREGISTRY000:Z5lfar1QrEnZZt9MYSWM7C6NLAE="}}, baseurl:"http://pithos.marathon.mesos", payload:io.Reader(nil), prepared:true}
2016/04/25 15:26:05 } -> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Server: Pithos
X-Amz-Id-2: 787a2e79-540c-42e9-bef1-391d5d824448
X-Amz-Request-Id: 787a2e79-540c-42e9-bef1-391d5d824448

242
<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CommonPrefixes><Prefix>docker/</Prefix></CommonPrefixes><Name>docker-registry</Name><Prefix></Prefix><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>gitconfig</Key><LastModified>2016-04-24T18:42:18.976Z</LastModified><ETag>"b7113b5b20151b0d061282ac13a0c75b"</ETag><Size>1838</Size><Owner><ID>user@email.com</ID><DisplayName>user@email.com</DisplayName></Owner><StorageClass>Standard</StorageClass></Contents></ListBucketResult>
```

Here's the log from pithos:

```
DEBUG [2016-04-24 18:41:47,030] qtp2032752946-249 - io.pithos.operations - handling operation:  :get-bucket
DEBUG [2016-04-24 18:42:10,310] qtp2032752946-249 - io.pithos.request - request:  {:ssl-client-cert nil, :remote-addr "10.43.128.3", :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0xb5014cd "clojure.core.async.impl.channels.ManyToManyChannel@b5014cd"], :headers {"authorization" "AWS BUNKHOUSEREGISTRY000:Gd3eYo1sFGjr7PfzIfOsZYtwImc=", "content-length" "1838", "x-amz-meta-s3cmd-attrs" "uid:1011/gname:tim.harper/uname:tim.harper/gid:1011/mode:33204/mtime:1460670462/atime:1461454336/md5:b7113b5b20151b0d061282ac13a0c75b/ctime:1460670462", "x-amz-date" "Sun, 24 Apr 2016 18:42:07 +0000", "host" "pithos.marathon.mesos", "content-type" "text/plain", "accept-encoding" "identity", "x-amz-storage-class" "STANDARD"}, :server-port 80, :servlet-request #object[org.eclipse.jetty.server.Request 0x532223a8 "(PUT /dockery-registry/gitconfig)@1394746280 org.eclipse.jetty.server.Request@532223a8"], :content-length 1838, :content-type "text/plain", :character-encoding nil, :uri "/dockery-registry/gitconfig", :server-name "pithos.marathon.mesos", :query-string nil, :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0x28204891 "HttpInputOverHTTP@28204891"], :scheme :http, :request-method :put}
DEBUG [2016-04-24 18:42:10,318] qtp2032752946-249 - io.pithos.operations - handling operation:  :put-object
DEBUG [2016-04-24 18:42:18,907] qtp2032752946-249 - io.pithos.request - request:  {:ssl-client-cert nil, :remote-addr "10.43.128.3", :ctrl #object[clojure.core.async.impl.channels.ManyToManyChannel 0x1db03660 "clojure.core.async.impl.channels.ManyToManyChannel@1db03660"], :headers {"authorization" "AWS BUNKHOUSEREGISTRY000:tV6vSw48zaZOsl4kxDH3/AlNINU=", "content-length" "1838", "x-amz-meta-s3cmd-attrs" "uid:1011/gname:tim.harper/uname:tim.harper/gid:1011/mode:33204/mtime:1460670462/atime:1461454336/md5:b7113b5b20151b0d061282ac13a0c75b/ctime:1460670462", "x-amz-date" "Sun, 24 Apr 2016 18:42:15 +0000", "host" "pithos.marathon.mesos", "content-type" "text/plain", "accept-encoding" "identity", "x-amz-storage-class" "STANDARD"}, :server-port 80, :servlet-request #object[org.eclipse.jetty.server.Request 0x7637cd39 "(PUT /docker-registry/gitconfig)@1983368505 org.eclipse.jetty.server.Request@7637cd39"], :content-length 1838, :content-type "text/plain", :character-encoding nil, :uri "/docker-registry/gitconfig", :server-name "pithos.marathon.mesos", :query-string nil, :body #object[org.eclipse.jetty.server.HttpInputOverHTTP 0xe46add4 "HttpInputOverHTTP@e46add4"], :scheme :http, :request-method :put}
DEBUG [2016-04-24 18:42:18,913] qtp2032752946-249 - io.pithos.operations - handling operation:  :put-object
DEBUG [2016-04-24 18:42:18,948] qtp2032752946-249 - io.pithos.stream - marking new block
DEBUG [2016-04-24 18:42:18,973] qtp2032752946-249 - io.pithos.stream - negative write, read whole stream
DEBUG [2016-04-24 18:42:18,974] qtp2032752946-249 - io.pithos.stream - closing after write
```

**Comment by schu** [comment]
Which version of Pithos are you using? I'm testing with tip of master. If you could push your distribution branch, I would love to have a look. Thanks.

**Comment by timcharper** [comment]
I'm using the last released precompiled JAR, downloaded from Github. pithos-0.7.4-standalone.jar

WRT to the fork, sure, I'll push it up.

**Comment by timcharper** [comment]
I unrolled my changes to make regionendpoint customizable and hardcoded it. Here's what I'm running docker distribution wise:

https://github.com/timcharper/distribution

**Comment by schu** [comment]
> I'm using the last released precompiled JAR, downloaded from Github. pithos-0.7.4-standalone.jar

master should work with the aforementioned steps. With 0.7.4 there is an issue regarding timestamps, which was fixed later (#78).

**Comment by timcharper** [comment]
Oh, great! Is there any chance you'll be cutting a `0.7.5` release soon?

**Comment by schu** [comment]
AFAIK @pyr is working on it, so yes :)

**Comment by timcharper** [comment]
Great! My docker build for pithos is set up to pull and run the latest release from github, so trying it once it's released will be nice and smooth.

**Comment by timcharper** [comment]
Ping on the release ? :)

**Comment by pyr** [comment]
Hi @timcharper sorry for taking so long. I will add support for more connection parameters and cut the relase. Sorry to keep you waiting.

**Comment by timcharper** [comment]
Okay, thank you!

**Comment by timcharper** [comment]
One last gentle nudge :)

**Comment by pyr** [comment]
@timcharper thanks for waiting: https://github.com/exoscale/pithos/releases/tag/0.7.5

**Comment by timcharper** [comment]
\o/ !!! thank you!

**Comment by timcharper** [comment]
Requests sign properly, now! Docker push works for somethings, however, I'm frequently experiencing cases where the push stalls after uploading 100% of the layer, indefinitely. I suspect some other issue is at play. :(

**Comment by pyr** [comment]
Hi @timcharper,

Can I ask you to open an issue with some details and debugging output for this problem?

Thanks!
