### ISSUE TITLE
pithos 0.7.4 and apache cassandra 3.5

### ISSUE THREAD

**Issue by mltest1234** [exoscale/pithos#91]
Hello,
I tried to use apache cassandra 3.5 together with pithos 0.7.4. 
But when i tried to configure a cassandra (java -jar pithos-0.7.4-standalone.jar -a install-schema)
i received an exception (see below). With apache cassandra 2.1.14 works everything smoothly.
If I understand an exception properly (for example: http://stackoverflow.com/questions/34117374/com-datastax-driver-core-exceptions-invalidqueryexception-unconfigured-table-sc or http://stackoverflow.com/questions/35355294/failing-to-connect-to-cassandra-through-phantom-nohostavailableexception) a datastax driver, that is used by pithos, does not support apache cassandra 3.5. Am I right? Are there any plans to support apache cassandra 3.5?

Stacktrace:
DEBUG [2016-05-06 12:46:00,187] main - io.pithos.config - building  :keystore  with  io.pithos.keystore/map-keystore
DEBUG [2016-05-06 12:46:00,192] main - io.pithos.config - building  :bucketstore  with  io.pithos.bucket/cassandra-bucket-store
DEBUG [2016-05-06 12:46:00,193] main - io.pithos.store - building cassandra store for:  localhost storage nil
ERROR [2016-05-06 12:46:00,732] main - io.pithos.config - invalid or incomplete configuration
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1230)
	at com.datastax.driver.core.Cluster.init(Cluster.java:157)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:245)
	at qbits.alia$connect.invoke(alia.clj:166)
	at io.pithos.store$cassandra_store.invoke(store.clj:26)
	at io.pithos.bucket$cassandra_bucket_store.invoke(bucket.clj:90)
	at clojure.lang.Var.invoke(Var.java:379)
	at io.pithos.config$instantiate.invoke(config.clj:89)
	at io.pithos.config$get_instance.invoke(config.clj:97)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$update_in.doInvoke(core.clj:5919)
	at clojure.lang.RestFn.invoke(RestFn.java:467)
	at io.pithos.config$init.invoke(config.clj:151)
	at io.pithos$_main.doInvoke(pithos.clj:66)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at io.pithos.main(Unknown Source)

**Comment by pyr** [comment]
Hi @mltest1234,

Thanks for the report. 0.7.6 will be tested against more recent versions of cassanda.

**Comment by pyr** [comment]
Hi @mltest1234 this should be fixed on master, can you confirm?

**Comment by mltest1234** [comment]
Yes. Fix on master will be perfect

**Comment by pyr** [comment]
Thanks!
